service: FirstServerlessProject

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:PutItem'
        - 'dynamodb:GetItem'
        - 'dynamodb:DeleteItem'
        - 'dynamodb:Scan'
      Resource:
        - Fn::GetAtt: [ChatTable, Arn]
    - Effect: Allow
      Action:
        - 'execute-api:ManageConnections'
      Resource:
        - 'arn:aws:execute-api:*:*:**/@connections/*'

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - http:
          path: firstSLS/hello
          method: get
  goodbye:
    handler: src/functions/goodbye.handler
    events:
      - http:
          path: firstSLS/goodbye
          method: post
  question:
    handler: src/functions/question.handler
    dependsOn:
      - SNSQuestionEvent
    events:
      - sns:
          arn: !Ref SNSQuestionEvent
          topicName: question-event

  # Web socket handlers
  ws-connection:
    handler: src/functions/ws/connection.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  ws-default:
    handler: src/functions/ws/default.handler
    events:
      - websocket:
          route: $default
  ws-sendMessage:
    handler: src/functions/ws/sendMessage.handler
    events:
      - websocket:
          route: sendMessage

plugins:
  - serverless-plugin-typescript
  - serverless-offline

resources:
  Resources:
    # SNS Test call
    SNSQuestionEvent:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Question Event Topic
        TopicName: question-event

    # Web socket implementations
    # Chatting DynTable
    ChatTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: 'connectionId'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'connectionId'
            KeyType: 'HASH'
        BillingMode: PAY_PER_REQUEST
        TableName: chatIdTable
